import random


list_of_fame = [
    ['Jane Austen, an English novelist,',
     'I want nothing but death.',
     'https://en.wikiquote.org/wiki/Jane_Austen'],
    ['Lucille Ball, an American actress,',
     'My Florida water.',
     'https://en.wikiquote.org/wiki/Lucille_Ball'],
    ['John Belushi, an American comedian,',
     "Just don't leave me alone.",
     'https://en.wikipedia.org/wiki/John_Belushi'],
    ['Humphrey Bogart, an American screen actor,',
     "Goodbye, kid. Hurry back.",
     "https://en.wikipedia.org/wiki/Humphrey_Bogart"],
    ['Winston Churchill, a British statesman,',
     "I'm so bored with it all.",
     "https://en.wikiquote.org/wiki/Winston_Churchill"],
    ['Kurt Cobain, an American musician,',
     "…it's better to burn out than to fade away.",
     "https://en.wikiquote.org/wiki/Kurt_Cobain"],
    ['Lady Diana Spencer',
     "My God, what's happened?",
     "https://en.wikiquote.org/wiki/Diana,_Princess_of_Wales"],
    ['Isadora Duncan, an American and French dancer,',
     "Farewell my friends, I go to glory!",
     "https://en.wikipedia.org/wiki/Isadora_Duncan"],
    ['Henrik Ibsen, a Norwegian playwright and poet,',
     "On the contrary!",
     "https://en.wikiquote.org/wiki/Henrik_Ibsen"],
    ['Stan Laurel, an English comic actor,',
     "I'd rather be skiing than doing what I'm doing.",
     "https://en.wikipedia.org/wiki/Stan_Laurel"],
    ['General John Sedgwick, a Union Army general in the American Civil War,',
     "They couldn't hit an elephant at this distance!",
     "https://en.wikiquote.org/wiki/John_Sedgwick"],
    ['Francis Albert Sinatra, an American singer,',
     "I'm losing.",
     "https://en.wikiquote.org/wiki/Frank_Sinatra"],
    ['Hunter Stockton Thompson, an American journalist,',
     "Relax - This won't hurt.",
     "https://en.wikiquote.org/wiki/Hunter_S._Thompson"],
    ['Mao Zedong, the Chairman of the Communist Party of China,',
     "I feel ill. Call the doctors.",
     "https://en.wikiquote.org/wiki/Mao_Zedong"],
    ['Virginia Woolf, a British writer,',
     "I don't think two people could have been happier than we have been.",
     "https://en.wikiquote.org/wiki/Virginia_Woolf"],
    ['Leonardo da Vinci, an Italian Renaissance architect, musician, inventor, engineer, sculptor, and painter,',
     "I have offended God and mankind because my work did not reach the quality it should have.",
     "https://en.wikiquote.org/wiki/Leonardo_da_Vinci"],
    ['Sid Vicious, bassist of the Sex Pistols,',
     "We made a death pact, and I have to accomplish my part of the deal. Please bury me next to my baby. Please bury me with my leather jacket, jeans and motorcycle boots. Goodbye. With love, Sid.",
     "https://en.wikiquote.org/wiki/Sid_Vicious"],
    ['Eleanor Roosevelt, a social activist, first lady and the wife of US President Franklin D. Roosevelt,',
     "Utter nonsense.",
     "https://en.wikiquote.org/wiki/Eleanor_Roosevelt"],
    ['Marco Polo, Venetian traveller and writer,',
     "I have not told half of what I saw.",
     "https://en.wikipedia.org/wiki/Marco_Polo"],
    ['Edgar Allan Poe, an American poet, novelist, short story writer,',
     "Lord help my poor soul.",
     "https://en.wikiquote.org/wiki/Edgar_Allan_Poe"],
    ['Pablo Ruiz Picasso, a Spanish artist,',
     "Drink to me, drink to my health, you know I can't drink any more.",
     "https://en.wikiquote.org/wiki/Pablo_Picasso"],
    ['Eva Peron, Argentinian First Lady,',
     "Eva is leaving.",
     "https://en.wikipedia.org/wiki/Eva_Peron"],
    ['Alvaro Obregon, Mexican politician,',
     "More totopos.",
     "https://en.wikipedia.org/wiki/Alvaro_Obregon"],
    ['Karl Marx, a German political philosopher, economist, historian, sociologist, journalist and revolutionary socialist,',
     "Last words are for fools who haven't said enough!",
     "https://en.wikiquote.org/wiki/Karl_Marx"],
    ['Howard Phillips Lovecraft, American author,',
     "Sometimes the pain is unbearable.",
     "https://en.wikipedia.org/wiki/H._P._Lovecraft"],
    ['Frida Kahlo, a Mexican painter,',
     "I hope the exit is joyful and hope never to return.",
     "https://en.wikiquote.org/wiki/Frida_Kahlo"],
    ['Thomas Jefferson, 3rd President of the United States,',
     "Is it the Fourth?",
     "https://en.wikiquote.org/wiki/Thomas_Jefferson"],
    ['Washington Irving, American author,',
     "I have to set my pillows one more night, when will this end already?",
     "https://en.wikiquote.org/wiki/Washington_Irving"],
    ['Ernesto "Che" Guevara, an Argentine Marxist revolutionary,',
     "I know you are here to kill me. Shoot, coward, you are only going to kill a man.",
     "https://en.wikiquote.org/wiki/Che_Guevara"],
    ['Richard Feynman, american physicist,',
     "I'd hate to die twice. It's so boring.",
     "https://en.wikiquote.org/wiki/Richard_Feynman"],
    ['Leonhard Euler, Swiss mathematician and physicist,',
     "I die.",
     "https://en.wikipedia.org/wiki/Leonhard_Euler"],
    ['Marie Antoinette, Queen of France,',
     "Pardon me, sir. I did not do it on purpose.",
     "https://en.wikiquote.org/wiki/Marie_Antoinette"],
    ['Francois Rabelais, a French humanist writer of satirical romances,',
     'I am going to seek a grand perhaps; draw the curtain, the farce is played.',
     'https://en.wikiquote.org/wiki/Francois_Rabelais'],
    ['Simon Bolivar, a South American revolutionary leader,',
     'Damn it, how will I ever get out of this labyrinth?',
     'https://en.wikiquote.org/wiki/Simon_Bolivar'],
    ['Millard Fillmore, the 13th president of the United States,',
     'The nourishment is palatable.',
     'https://en.wikiquote.org/wiki/Millard_Fillmore'],
    ['Albert Sidney Johnston, a general in the Confederate States Army,',
     'Yes... and I fear seriously',
     'https://en.wikipedia.org/wiki/Albert_Sidney_Johnston'],
    ['Dylan Thomas, a Welsh poet and writer,',
     "I've had 18 straight whiskies... I think that's the record.",
     'https://en.wikiquote.org/wiki/Dylan_Thomas'],
    ['Henry Ward Beecher, an American Congregationalist clergyman,',
     'Now comes the mystery.',
     'https://en.wikiquote.org/wiki/Henry_Ward_Beecher']
]


def return_random_quote():
    rand_quote = list_of_fame[random.randrange(len(list_of_fame))]
    return rand_quote


# rand_quote = return_random_quote()
# # for i in range(len(list_of_fame)):
# #     print(list_of_fame[i][0] + ' said:')
# #     print('"' + list_of_fame[i][1] + '"')
# #     print(list_of_fame[i][2])
# print(rand_quote[0] + ' said:')
# print(rand_quote[1])
# print(rand_quote[2])
# print(len(list_of_fame))
